name: buddybrew
description: A social app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  google_sign_in: 6.1.5
  crypto: ^3.0.3
  font_awesome_flutter: ^10.5.0
  google_fonts: 5.1.0
  rxdart: ^0.27.7
  json_annotation: ^4.8.1
  supabase_flutter: ^1.10.11
  flutter_appauth: ^6.0.2
  sign_in_with_apple: ^5.0.0
  flutter_svg: ^2.0.7
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^11.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/covers/
    - assets/congrats.gif
