// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Vsv6QVncdZ-UpPHAdWZ27EMj8Esb_KY',
    appId: '1:819999562577:android:7ea3dc7e9c507d2df2d170',
    messagingSenderId: '819999562577',
    projectId: 'buddybrew-app',
    storageBucket: 'buddybrew-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuxr0phAcUo5WGXFcOe7u07HlS4-T-mZs',
    appId: '1:819999562577:ios:e48552758b88ac31f2d170',
    messagingSenderId: '819999562577',
    projectId: 'buddybrew-app',
    storageBucket: 'buddybrew-app.appspot.com',
    androidClientId: '819999562577-8jpktj5okk947jdl6pbot2mg5pmgs0lk.apps.googleusercontent.com',
    iosClientId: '819999562577-qsrnh4h9dhdioj9ios9j6p5r82kg7p84.apps.googleusercontent.com',
    iosBundleId: 'app.buddybrew.app',
  );
}
